In [2]:
import tensorflow as tf
print(tf.__version__)

2.11.0


In [2]:
# Creating tensors
scalar =tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
#Check the number of dimensions of a tensor 
scalar.ndim

0

In [4]:
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>

In [5]:
#Check the dimension of the vector
vector.ndim


1

In [6]:
#Create a matrix 
matrix = tf.constant([[10,7],[7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]])>

In [7]:
matrix.ndim


2

In [8]:
#create another matrix
matrix_2=tf.constant([[10.,7.],[3.,2.],[8.,9.]],dtype=tf.float16)#specify the data type with dtype
matrix_2

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [9]:
#whats the number of dimensions in matrix_2
matrix_2.ndim

2

In [10]:
#Let's Create a tensor
tensor = tf.constant([[[1,2,3,],
                      [4,5,6]],
                      [[7,8,9],
                      [10,11,12]],
                     [[13,14,15],
                     [16,17,18]]])
tensor


<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])>

In [11]:
tensor.ndim

3

In [12]:
#Creating tensors with tf.Variable



In [13]:
#Create the same tensor as  above using tfVariable
changeable_tensor=tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor,unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7])>)

In [14]:
#Lets try chnaging element in changeable  tensor
#changeable_tensor[0]=7 ------------>wouldn't word
changeable_tensor[0].assign(7)
changeable_tensor



<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7])>

In [15]:
# unchangeable_tensor[0]=7
unchangeable_tensor[0].asssign(7)
unchangeable_tensor

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'asssign'

# Creating random tensors

In [18]:
# lets create two random but same tensors 
random_1 = tf.random.Generator.from_seed(42) # set seed for reproducibility
random_1 = random_1.normal(shape=(3,2)) 

random_2= tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))

random_1,random_2,random_1==random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [7]:
# Shuffle a tensor
not_shuffled = tf.constant([[10,7],
                           [3,4],
                           [2,5]])
tf.random.shuffle(not_shuffled)



<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]])>

In [8]:
tf.random.shuffle(not_shuffled) 

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  5],
       [ 3,  4]])>

In [17]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled,seed=42) 

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]])>

In [18]:
import numpy as np
numpy_A = np.arange(1,25,dtype=np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [20]:
A = tf.constant(numpy_A,shape=(3,2,4))
A

<tf.Tensor: shape=(3, 2, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[17, 18, 19, 20],
        [21, 22, 23, 24]]])>